### ISSUE TITLE
Replace modules using deprecated methods

### ISSUE THREAD

**Issue by awstomburge** [aws-samples/aws-sdk-js-notes-app#28]
### Is your feature request related to a problem? Please describe.
The notes-app uses the microphone-stream module to record audio. This module is using the deprecated method of createScriptProcessor (https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createScriptProcessor)

### Describe the solution you'd like
I would suggest a switch to a module that is using the AudioWorklet replacement for createScriptProcessor.

**Comment by trivikr** [comment]
Example https://github.com/aws-samples/amazon-transcribe-streaming-example-webapp-audiostream
