### ISSUE TITLE
Use ESModules in notes app backend

### ISSUE THREAD

**Issue by trivikr** [aws-samples/aws-sdk-js-notes-app#4]
### Is your feature request related to a problem? Please describe.
Not a problem, but it would be good to show Node.js using ESM as:
* Node.js 10.x is the last LTS version not supporting ESM, and it's going end-of-life on April 30th, 2021.
* JavaScript package maintainers are excited about dropping support for commonjs format. Example blog post: https://blog.sindresorhus.com/get-ready-for-esm-aa53530b3f77

ESM comes with many benefits, like language-level syntax, browser support, defaults to strict mode, async loading, top-level await, improved static analysis & tree-shaking, and more.
* Overview on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules
* Node.js docs on ESM: https://nodejs.org/api/esm.html

### Describe the solution you'd like
Use ESM modules in the todo app backend by setting `"type": "module"` in package.json.
Docs: https://nodejs.org/api/esm.html#esm_enabling

### Describe alternatives you've considered
Sticking with using commonjs for the backend.

**Comment by trivikr** [comment]
Experimental commits can be viewed in https://github.com/trivikr/aws-sdk-js-todo-app/commits/use-esm

Not going ahead right now as:
* Webpack doesn't yet support `output.libraryTarget: 'module'` https://github.com/webpack/webpack/issues/2933
* minor: ESM support is experimental in ts-node https://github.com/TypeStrong/ts-node/issues/1007
* minor: webpack doesn't support ES6 config file https://stackoverflow.com/a/65882354

**Comment by cspotcode** [comment]
You probably know this, but just to clarify, ts-node's ESM support is experimental out of necessity, because node's ESM loader hooks are experimental.  So there's no way we can guarantee a stable feature built on unstable node APIs.

Even though node's ESM feature is "stable," the reality is that it's still limited compared to CommonJS.

**Comment by trivikr** [comment]
No longer needed, as we now bundle through aws_cdk.aws_lambda_nodejs https://github.com/aws-samples/aws-sdk-js-notes-app/pull/122
